import { Request, Router } from "express";
import mongoose from "mongoose";

export type SupportedLanguage = "en" | "ja";

export interface UserRef {
  type: mongoose.Types.ObjectId;
  ref: string;
}

export interface UserI {
  _id?: string;
  firstName: string;
  lastName: string;
  username: string;
  password: string;
  role: {
    type: string;
    default: string;
  };
  language: SupportedLanguage;
}

export interface UserModel extends UserI {
  createdAt: {
    type: Date;
    default: Date;
  };
  comparePassword(candidatePassword: string): Promise<boolean>;
}

export interface CallI {
  id: string;
  name: string;
}

export interface CallModel extends CallI {
  createdAt: {
    type: Date;
    default: Date;
    expires: number;
  };
}

export interface ContainersI {
  id?: string;
  user: UserRef;
  containers: Array<string>;
}

export interface ContainersModel extends ContainersI {
  user: UserRef;
}

export interface ProductI {
  code: string;
  name: string;
  brand: string;
  description: string;
  container: string;
  tags: Array<string>;
  amount: number;
  unit: string;
  src?: string;
  avgDaysToExpiration?: number;
}

export type ProductModel = ProductI & mongoose.Document;

export interface RecipeI {
  id?: string;
  user: UserRef;
  name: string;
  minutes: number;
  materials: Array<string>;
  numServings: number;
  ingredients: Array<string>;
  steps: Array<string>;
  description: string;
  link: string;
  generatedWith?: Array<string>;
  added: Date;
  wasAutogenerated: boolean;
  language: SupportedLanguage;
}

export type RecipeModel = RecipeI & mongoose.Document;

export interface ItemI {
  id?: string;
  user: UserRef;
  code: string;
  name: string;
  brand: string;
  description: string;
  container: string;
  expiration: Date;
  tags: Array<string>;
  amount: number;
  unit: string;
  src: string;
  added: Date;
  deleted: boolean;
}

export type ItemModel = ItemI & mongoose.Document;

export interface VerifiedUserRequest<T> extends Request<any, any, any, T> {
  user: UserI;
  session: { userID: any };
  file: { filename: string };
}

export interface AnyUserRequest<T> extends Request<any, any, any, T> {}

export interface StorageHistoryParams {
  limit: number;
  offset: number;
}

export interface Route {
  path: string;
  router: Router;
}

export interface File {
  filename: string;
}
